// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDC-EDE7d1aOzLZrgzyq9Gi-H4LxjEsYCU',
    appId: '1:204717000834:web:b5d7aeff32c2a510ad8c9b',
    messagingSenderId: '204717000834',
    projectId: 'flutter-firebase-87542',
    authDomain: 'flutter-firebase-87542.firebaseapp.com',
    storageBucket: 'flutter-firebase-87542.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCc6kFa_IQ6CFVeOOhiot5LHjxTZXc1dPA',
    appId: '1:204717000834:android:97e14f3d3fc4d567ad8c9b',
    messagingSenderId: '204717000834',
    projectId: 'flutter-firebase-87542',
    storageBucket: 'flutter-firebase-87542.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAj8KtnKw04GRs6TiOgPG3RqDkCUhOQHl4',
    appId: '1:204717000834:ios:46e9bb723d5bbb7dad8c9b',
    messagingSenderId: '204717000834',
    projectId: 'flutter-firebase-87542',
    storageBucket: 'flutter-firebase-87542.appspot.com',
    androidClientId: '204717000834-k2a2jclo06tf8v66aocntujtinqgppa5.apps.googleusercontent.com',
    iosClientId: '204717000834-7q4292u4klm30gutj5atk4d6aevt9elp.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebase',
  );
}
